"""create node, node_state, and audit_log tables

Revision ID: 2252842c9c90
Revises: 
Create Date: 2026-09-08 14:34:03.248402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2252842c9c90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('tailnet', sa.String(length=255), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('os_version', sa.String(length=128), nullable=True),
    sa.Column('client_version', sa.String(length=64), nullable=True),
    sa.Column('addresses', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('endpoints', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('machine_key', sa.String(length=256), nullable=True),
    sa.Column('node_key', sa.String(length=256), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('key_expiry_disabled', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_available', sa.Boolean(), nullable=False),
    sa.Column('telemetry_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_hostname'), 'nodes', ['hostname'], unique=False)
    op.create_index(op.f('ix_nodes_is_online'), 'nodes', ['is_online'], unique=False)
    op.create_index(op.f('ix_nodes_last_seen'), 'nodes', ['last_seen'], unique=False)
    op.create_index(op.f('ix_nodes_name'), 'nodes', ['name'], unique=False)
    op.create_index(op.f('ix_nodes_node_id'), 'nodes', ['node_id'], unique=True)
    op.create_index(op.f('ix_nodes_os'), 'nodes', ['os'], unique=False)
    op.create_index('ix_nodes_os_is_online', 'nodes', ['os', 'is_online'], unique=False)
    op.create_index(op.f('ix_nodes_tailnet'), 'nodes', ['tailnet'], unique=False)
    op.create_index('ix_nodes_tailnet_is_online', 'nodes', ['tailnet', 'is_online'], unique=False)
    op.create_index(op.f('ix_nodes_user'), 'nodes', ['user'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('event_category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_category'), 'audit_logs', ['event_category'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index('ix_audit_logs_event_type_created_at', 'audit_logs', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_node_id'), 'audit_logs', ['node_id'], unique=False)
    op.create_index('ix_audit_logs_node_id_created_at', 'audit_logs', ['node_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_index('ix_audit_logs_severity_created_at', 'audit_logs', ['severity', 'created_at'], unique=False)
    op.create_table('node_states',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('is_compliant', sa.Boolean(), nullable=False),
    sa.Column('compliance_status', sa.String(length=64), nullable=False),
    sa.Column('firewall_enabled', sa.Boolean(), nullable=True),
    sa.Column('disk_encryption_enabled', sa.Boolean(), nullable=True),
    sa.Column('screen_lock_enabled', sa.Boolean(), nullable=True),
    sa.Column('antivirus_active', sa.Boolean(), nullable=True),
    sa.Column('tailscale_ssh_enabled', sa.Boolean(), nullable=True),
    sa.Column('key_expired', sa.Boolean(), nullable=False),
    sa.Column('os_version', sa.String(length=128), nullable=True),
    sa.Column('client_version', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('derp_region', sa.String(length=64), nullable=True),
    sa.Column('packet_loss', sa.Float(), nullable=True),
    sa.Column('rx_bytes', sa.BigInteger(), nullable=True),
    sa.Column('tx_bytes', sa.BigInteger(), nullable=True),
    sa.Column('posture_checks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('telemetry_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_node_states_compliance_recorded_at', 'node_states', ['compliance_status', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_node_states_compliance_status'), 'node_states', ['compliance_status'], unique=False)
    op.create_index(op.f('ix_node_states_is_compliant'), 'node_states', ['is_compliant'], unique=False)
    op.create_index(op.f('ix_node_states_is_online'), 'node_states', ['is_online'], unique=False)
    op.create_index(op.f('ix_node_states_node_id'), 'node_states', ['node_id'], unique=False)
    op.create_index('ix_node_states_node_id_recorded_at', 'node_states', ['node_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_node_states_recorded_at'), 'node_states', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_states_recorded_at'), table_name='node_states')
    op.drop_index('ix_node_states_node_id_recorded_at', table_name='node_states')
    op.drop_index(op.f('ix_node_states_node_id'), table_name='node_states')
    op.drop_index(op.f('ix_node_states_is_online'), table_name='node_states')
    op.drop_index(op.f('ix_node_states_is_compliant'), table_name='node_states')
    op.drop_index(op.f('ix_node_states_compliance_status'), table_name='node_states')
    op.drop_index('ix_node_states_compliance_recorded_at', table_name='node_states')
    op.drop_table('node_states')
    op.drop_index('ix_audit_logs_severity_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_node_id_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_node_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_event_type_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_nodes_user'), table_name='nodes')
    op.drop_index('ix_nodes_tailnet_is_online', table_name='nodes')
    op.drop_index(op.f('ix_nodes_tailnet'), table_name='nodes')
    op.drop_index('ix_nodes_os_is_online', table_name='nodes')
    op.drop_index(op.f('ix_nodes_os'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_node_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_name'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_last_seen'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_is_online'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_hostname'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
